@startuml slack_db_model

entity user {
    * user_id [PK]
    --
    * user_name
}

entity workspace {
    * workspace_id [PK]
    --
    * workspace_name
}

entity belong_to_workspace {
    * workspace_id [FK]
    * user_id [FK]
    --
    * when_belonged
}

entity channel {
    * channel_id [PK]
    --
    * channel_name
    * workspace_id [FK]
}

entity belong_to_channel {
    * channel_id [FK]
    * user_id [FK]
    --
    * when_belonged
}

entity own_channels {
    * workspace_id [FK]
    * channel_id [FK]
    --
    * when_created
}

entity message {
    * message_id [PK]
    --
    * thread_id
    * user_id [FK]
    * channel_id [FK]
    * content
    * when_created
    * when_updated
}

user ||--o{ belong_to_workspace
user ||--o{ belong_to_channel
user ||--o{ message
workspace ||--o{ belong_to_workspace
channel ||--o{ belong_to_channel
workspace ||--o{ own_channels
own_channels ||--|| channel
channel ||--o{ message